pymmcore_remote/_mmcore_plus.py
=> onMDAFrameReady

pymmcore_remote/_client.py, pymmcore_remote/_serialize.py, pymmcore_remote/_tests/test_client.py, pymmcore_remote/qcallbacks.py, setup.cfg
fixes ser/des of MDAEvent object
=> fix mda event serialization

.github/workflows/test_and_deploy.yml, .gitignore, install_mm.py, pymmcore_remote/_client.py, pymmcore_remote/_mmcore_plus.py, pymmcore_remote/_tests/test_client.py, pymmcore_remote/_util.py, setup.cfg
Fixes an issue with setting the deviceAdapter search paths, and add `install_mm.py` with tests
=> fix find-micromanager, add CI tests

README.md, pymmcore_plus/__init__.py, pymmcore_plus/_serialize.py, pymmcore_plus/_tests/test_core.py, pymmcore_plus/_tests/test_serialize.py, pymmcore_plus/_tests/test_server.py, pymmcore_plus/core/_mmcore_plus.py, pymmcore_plus/install.py, pymmcore_plus/server/_pyrocore.py, pymmcore_plus/server/_pyrocore.pyi, setup.cfg
=> improve test coverage

pymmcore_plus/client/callbacks/qcallback.py
=> add new configSet signal to qcallback

pymmcore_plus/_serialize.py
fixes a bug when too many shared memory files are open
=> fix shared mem

pymmcore_plus/core/_config.py
noticed when trying to learn more about config objects
=> fix func name in docstring

.github/workflows/test_and_deploy.yml
To catch breaks caused by changed upstream. e.g. #63
=> Run test suite once weekly

.github/workflows/test_and_deploy.yml
in the hopes that it will fix flaky tests
=> remove caching

pymmcore_plus/_tests/test_core.py, pymmcore_plus/core/_mmcore_plus.py
=> restore setPosition overloading

pymmcore_plus/install.py
Adds a `--yes` flag to `python -m pymmcore_plus.install` that will never ask the user for input (automatically overwrites pre-existing installs and doesn't use sudo).  Useful for automation
=> add quiet `--yes` install flag

pymmcore_plus/core/_mmcore_plus.py
leftover from threading adventures
=> remove leftover debug statements

.readthedocs.yml
looks like RTD doesn't support 3.9 yet
=> fix python version in RTD build

README.md, docs/conf.py, docs/contributing.md
We should also:
1. Add a link to the github about section
2. Have RTD build on PRs (only @tlambert03 can enable that)
=> Doc follow ups

pymmcore_plus/_util.py
fixes: https://github.com/tlambert03/pymmcore-plus/issues/119
also cleaned up some unused things in `_util.py`
=> Ensure import of QtWidgets in `check_qt_app`

pymmcore_plus/_tests/test_mda.py, pymmcore_plus/mda/_engine.py
Fixes https://github.com/tlambert03/pymmcore-plus/issues/130
=> fix: make mda engine exit gracefully after an exception

.pre-commit-config.yaml, pyproject.toml, src/pymmcore_plus/_logger.py, src/pymmcore_plus/core/_device.py, src/pymmcore_plus/core/_metadata.py, src/pymmcore_plus/core/_mmcore_plus.py, src/pymmcore_plus/core/events/__init__.py, src/pymmcore_plus/core/events/_device_signal_view.py, src/pymmcore_plus/core/events/_prop_event_mixin.py, src/pymmcore_plus/core/events/_psygnal.py, src/pymmcore_plus/core/events/_qsignals.py, src/pymmcore_plus/install.py, src/pymmcore_plus/mda/_runner.py, src/pymmcore_plus/mda/events/__init__.py, src/pymmcore_plus/mda/events/_protocol.py, src/pymmcore_plus/remote/client/_client.py, src/pymmcore_plus/remote/server/_pyrocore.py
this enables mypy strict mode, and fixes all remaining issues
=> refactor: enable strict typing

.github/workflows/test_and_deploy.yml, pyproject.toml
=> build: support python 3.11 

.pre-commit-config.yaml, pyproject.toml
couldn't force push to #175...
=> style: update precommit

src/pymmcore_plus/_logger.py, src/pymmcore_plus/mda/_runner.py
use internal logger with better control over logging level
=> fix: fix logging import

tests/test_core.py, tests/test_events.py
fix test after the newest micromanager demo cfg.
=> fix: update for newest micromanager demo cfg

.pre-commit-config.yaml, pyproject.toml, src/pymmcore_plus/_cli.py, src/pymmcore_plus/core/_constants.py, src/pymmcore_plus/core/_mmcore_plus.py, src/pymmcore_plus/core/events/_prop_event_mixin.py, src/pymmcore_plus/core/events/_protocol.py, src/pymmcore_plus/install.py, src/pymmcore_plus/mda/_runner.py, src/pymmcore_plus/mda/events/_protocol.py, src/pymmcore_plus/remote/client/callbacks/qcallback.py, src/pymmcore_plus/remote/server/_server.py, tests/test_events.py
updates pre-commit and fixes the recent typing issue with PSignalInstance
=> style: update pre-commit

src/pymmcore_plus/core/_mmcore_plus.py
=> fix: small fix in get state

tests/test_cli.py
with https://github.com/pymmcore-plus/useq-schema/pull/102 these two tests will begin failing
=> fix: don't use invalid plans in test

docs/_hooks.py, docs/api/utils.md, docs/guides/logging.md, mkdocs.yml, src/pymmcore_plus/__init__.py, src/pymmcore_plus/_cli.py, src/pymmcore_plus/_logger.py, src/pymmcore_plus/_util.py, src/pymmcore_plus/core/_mmcore_plus.py, tests/conftest.py, tests/test_cli.py
=> feat: add logging to file and cli command

src/pymmcore_plus/core/_sequencing.py, src/pymmcore_plus/mda/_engine.py, tests/test_sequencing.py
This makes the combination of events user customizeable
=> feat: add attribute to control hardware sequencing

.github/workflows/test_and_deploy.yml, .pre-commit-config.yaml, pyproject.toml, src/pymmcore_plus/_cli.py, src/pymmcore_plus/core/_sequencing.py, src/pymmcore_plus/mda/_engine.py, src/pymmcore_plus/mda/_runner.py, tests/conftest.py, tests/test_cli.py, tests/test_mda.py
This brings support for pydantic2 via useq v0.4.0
It also uses the new fov attributes on useq grid plans in v0.4.0
=> feat: use new fov on useq grid objects, support pydantic2

src/pymmcore_plus/mda/_engine.py, src/pymmcore_plus/mda/_runner.py, tests/test_sequencing.py
=> refactor: make hardware sequencing detection opt-in

src/pymmcore_plus/mda/_engine.py, tests/test_mda.py
closes #117 .  implements support for leaving the shutter open if `MDAEvent.keep_shutter_open` is True
=> feat: implement keep shutter open for engine

docs/api/mda.md, docs/contributing.md, docs/examples/following_changes_in_core.md, docs/examples/mda.md, docs/guides/conditional_events.md, docs/guides/custom_engine.md, docs/guides/event_driven_acquisition.md, docs/guides/mda_engine.md, docs/index.md, docs/install.md, examples/event_driven_acquisition.py, mkdocs.yml
cc @MakerTobey  ... as promised :)
=> docs: adding acquisition engine docs

docs/examples/pycro-manager-api.md, docs/guides/pycromanager_migration.md, examples/pycro-api.py, mkdocs.yml
borrowed from the example given at https://github.com/micro-manager/micro-manager/pull/1670#issuecomment-1678965846
=> docs: add pycro-manager API adapter as an educational example

pyproject.toml, src/pymmcore_plus/core/_mmcore_plus.py, tests/test_core.py
finishing on https://github.com/micro-manager/pymmcore/issues/78, thanks to @marktsuchida in https://github.com/micro-manager/pymmcore/pull/80
=> feat: add getMultiROI method, bump core dep

src/pymmcore_plus/_util.py
only look for folders when looking for device adapters
=> fix: fix find micromanager bug

src/pymmcore_plus/_util.py, src/pymmcore_plus/install.py, tests/test_cli.py, tests/test_model.py
fixes an issue with detaching a mounted dmg when a previous mount exists
=> fix: some fixes to mmcore install on macos

tests/test_thread_relay.py
=> test: skip flaky thread tests

.github/workflows/test_and_deploy.yml, pyproject.toml, src/pymmcore_plus/mda/_runner.py
just needs a minor change to make tests pass with MagicMock
=> feat: support py312

src/pymmcore_plus/install.py
shows the progress bar on windows during installation (while still not requiring user input)
=> chore: convert verysilent to silent

src/pymmcore_plus/core/_state.py
compatibility with https://github.com/micro-manager/pymmcore/releases/tag/v11.0.0.71.0
=> fix: Remove unused fields from SystemInfoDict for mmcore11 compatibility

.github/workflows/test_and_deploy.yml, pyproject.toml, src/pymmcore_plus/core/events/__init__.py
something is happening with pyqt on windows.  trying to fix here
=> fix: trying to fix windows tests

src/pymmcore_plus/install.py
name parsing needed a fix in delimiter for windows
fixes #300
=> fix: fix available version lookup on windows

src/pymmcore_plus/mda/handlers/_ome_zarr_writer.py, tests/test_handlers/test_ome_zarr.py
The zarr writer fails for me if I have only a partly set up MDASequence. Does it fail for you as well?
Will see if I can fix it.
=> fix: Zarr part mda

src/pymmcore_plus/mda/_engine.py
similar to https://github.com/micro-manager/AcqEngJ/pull/108
fixes #306 by calling `stopStageSequence` prior to `loadStageSequence` in the MDAEngine
=> fix: avoid hardware errors while running sequences with NIDAQ stages

src/pymmcore_plus/mda/_engine.py
This PR fixes a bug when we update the z_correction delta for each position.
=> fix: fix autofocus z_correction delta

.github/workflows/test_and_deploy.yml, pyproject.toml, src/pymmcore_plus/_util.py
=> fix: Fix pyside2 issue when disconnecting listeners_connected

src/pymmcore_plus/mda/_engine.py
undoes the change I did in #353 
cc @linshaova, will release in a moment
=> fix: fix setup sequence

.github/workflows/ci.yml, pyproject.toml, src/pymmcore_plus/core/events/_psygnal.py, src/pymmcore_plus/mda/events/_psygnal.py, tests/test_events.py
will help with https://github.com/pymmcore-plus/pymmcore-widgets/issues/300
=> feat: make CMMCoreSignaler and MDASignaler signal groups

src/pymmcore_plus/mda/_engine.py
fixes an issue that may arise when extracting metadata from the camera tags during sequenced acquisition
=> fix: fix failure to collect elapsed time during sequenced acquisition

src/pymmcore_plus/core/_mmcore_plus.py
the part of #365  that I actually should have included
=> feat:  enable StrictInitializationChecks

docs/cli.md, mkdocs.yml, pyproject.toml, src/pymmcore_plus/_build.py, src/pymmcore_plus/_cli.py
Adds documentation  about the CLI
=> docs: document cli

docs/guides/custom_engine.md, docs/guides/event_driven_acquisition.md, docs/guides/mda_engine.md
Typos and broken links, plus a small note (feel free to remove that commit if you don't think it belongs).
=> docs: fix typos etc.

.github/workflows/ci.yml
until we fix the wheel situation for py3.13 on pypi https://github.com/micro-manager/pymmcore/issues/125
=> ci: don't test py3.13 for now

.github/workflows/ci.yml, tests/test_model.py
I think this PR in pymmcore-nano fixes an issue that caused me to skip a particular test here. 
https://github.com/pymmcore-plus/pymmcore-nano/pull/33
unskipping with this PR
=> test: unskip test on pymmcore-nano

pyproject.toml
=> docs: pin mkdocs-autorefs

.github/workflows/ci.yml, .pre-commit-config.yaml, pyproject.toml, src/pymmcore_plus/__init__.py, src/pymmcore_plus/_accumulator.py, src/pymmcore_plus/_cli.py, src/pymmcore_plus/_discovery.py, src/pymmcore_plus/_logger.py, src/pymmcore_plus/_util.py, src/pymmcore_plus/core/_mmcore_plus.py, src/pymmcore_plus/install.py, tests/test_cli.py, tests/test_install.py, tests/test_model.py
This PR refactors how we discover micro-manager installations
=> refactor: improve device discovery structure
