pymmcore-plus/pymmcore-plus

pymmcore_plus/_util.py

If you follow the steps in the Docker file for pymmcore (https://github.com/micro-manager/pymmcore/blob/main/Dockerfile)
then you end up with an installation in `/usr/local/lib/micro-manager/`
Also, paths are case senstive on linux hence so search for both capital
and lowercase `m` in the glob.
Finally, added the searched path to the logger if nothing was found in
case people have non-standard install locations.
---
Annoyingly however this won't automatically grab the demo config as the install instructions don't move it to `/usr/local/lib/micro-manager`  so you still need to explicitly locate the path

Add automatic micromanager discovery for linux

---

pymmcore_plus/core/_mmcore_plus.py

Depending on user configuration setting the channel can have a side effect of changing the exposure. This then overrides the event exposure. Since the event is a more local config than the channel config it should take precedence for setting the exposure.

Set exposure after setting channel in run_mda

---

pymmcore_plus/core/_mmcore_plus.py
pymmcore_plus/core/_signals.py

This allows for working around issues with the
`onConfigGroupChanged` signal as discussed at
https://github.com/micro-manager/mmCoreAndDevices/issues/25
Closes: #25 
If this makes sense I'll make a follow PR for napari-micromanager

Add new `configSet` signal.

---

pymmcore_plus/_tests/test_core.py
pymmcore_plus/core/_constants.py
pymmcore_plus/core/_mmcore_plus.py

Adds two new methods:
`getDeviceProperties` - returns a dict of `{propName: value}` for a given device label
examples:
```py
{
'Description': 'Demo objective turret driver',
'HubID': '',
'Label': 'Nikon 10X S Fluor',
'Name': 'DObjective',
'State': '1',
'Trigger': '-'
}
```
`getDeviceSchema` - returns a schema dict (in json schema format) describing all of the properties (and their allowed values) for a given device_label
example:
```py
{
'title': 'DObjective',
'description': 'Demo objective turret',
'type': 'object',
'properties': {
'Description': {'type': 'string', 'readOnly': 'true', 'default': 'Demo objective turret driver'},
'HubID': {'type': 'string', 'readOnly': 'true', 'default': ''},
'Label': {
'type': 'string',
'enum': [
'Nikon 10X S Fluor',
'Nikon 20X Plan Fluor ELWD',
'Nikon …
```

add getDeviceSchema and getDeviceProperties methods

---

pymmcore_plus/core/_mmcore_plus.py

Some RGB cameras will return 32 bit 2D images, which requires the user to construct of a view of the array with a different dtype (uint8) and shape (w, h, 4) to  view the "proper" image intensities.  This PR modifies `getImage` and `popNextImage` to provide the "correct" image shape and dtype in these conditions

add fix_image for cameras with `getNumberOfComponents` != 1

---

pymmcore_plus/core/_mmcore_plus.py

fixes the order of #36.
I'm not sure how global this is, but it looks like micro-manager may return 8 bit color images as 32 bits in BGRA order (not RGBA).  this PR fixes that

Change order of channels in `_fix_image` to BGRA

---

pymmcore_plus/_tests/test_client.py
pymmcore_plus/_tests/test_core.py
pymmcore_plus/core/_mmcore_plus.py

For the methods that return `Configuration` objects:
```
"getConfigData",
"getConfigGroupState",
"getConfigGroupStateFromCache",
"getConfigState",
"getSystemState",
"getSystemStateCache",
```
this PR will default to returning a `pymmcore_plus.Configuration` which has a number of [conveniences](https://github.com/tlambert03/pymmcore-plus/blob/f8bc9b7736b0a2779ee42d4e4e24a2eff94569bf/pymmcore_plus/core/_config.py#L45-L57) over the native object.  
Because this adds a little overhead, these all also now take a `native=` parameter.  When `native == True`, the native pymmcore.Configuration object will be returned, avoiding the overhead of conversion

Return better config objects

---

pymmcore_plus/_serialize.py
pymmcore_plus/_tests/test_client.py
pymmcore_plus/_tests/test_core.py
pymmcore_plus/core/_mmcore_plus.py

related to #28 ... this reimplements `setProperty` to guarantee that an event is emitted if a property is changed using pymmcore.  It can't guarantee that an event will be emitted if it happens internal to the device adapter (and if the device adapter doesn't emit it), but it's a bit better.
@ianhi... now that I understand the issue slightly better what would you think about removing the `configSet` signal that we recently added and instead just reusing the `configGroupChanged` signal?  using a similar pattern to what I did in this PR:
```py
with self.events.configGroupChanged.blocked():
super().setConfig(groupName, configName)
self.events.configGroupChanged.emit(groupName, configName)
```
is there a specific case where we wanted the native signal and the pymmcore-plus signal to have …

add setProperty override that emits propertyChanged

---

pymmcore_plus/_tests/test_client.py
pymmcore_plus/core/_mmcore_plus.py

Otherwise you can end up waiting for as long as the interval in the
sequence is (easily 10 or 15 minutes)
The test fails locally without the fix and passes with.  Using `time.sleep` instead of `waitSignals` I wasn't able get the ordering of events to work properly - however I'm not sure I'm actually using qtbot correctly here.

ENH: Check for mda canceled while waiting

---

pymmcore_plus/_serialize.py
pymmcore_plus/_tests/test_client.py
pymmcore_plus/_tests/test_serialize.py
pymmcore_plus/core/_mmcore_plus.py

fixes #44 
This still doesn't fix the case of using the `native=True` option (returning a native `pymmcore` objects) ... but those should be less likely.
Tried to find a way to make sure we can serialize everything needed... but it was difficult

Fix serialization of Configuration and Metadata objects

---

setup.cfg

This is the version built with proper threading support which is important on many scopes and will crash the callback system.
See https://github.com/micro-manager/pymmcore/issues/49 for more information.

Set minimum pymmcore version

---

pymmcore_plus/client/_client.py
pymmcore_plus/core/_mmcore_plus.py
pymmcore_plus/server/__init__.py
pymmcore_plus/server/_server.py

This should hopefully protect from having to restart hardware/computers in order to restore connections that we might lose a reference to.
I can add tests but wanted to open first to get feedback if this is an ok strategy - in particular https://stackoverflow.com/a/14986946/835607 has me kinda spooked and I'm not 100% clear that my weakref trickery is an ok thing to do.
Fixes: https://github.com/tlambert03/pymmcore-plus/issues/42

Always call `unloadAllDevices`

---

pymmcore_plus/_tests/test_core.py
pymmcore_plus/core/_signals.py

Something about the way the signals we're being aliased on the `CMMCoreSignaler` object was not working so the `XYStagePosition` callback was not functioning. It's a bit confusing because I think this used to work but now isn't ??
First commit fails pytest locally, just pushing that to see if it fails CI as well.
Next commit does the aliasing using properties (https://stackoverflow.com/a/11050226/835607) which seems to fix things. I will push that after the tests run.
Fixes: https://github.com/tlambert03/pymmcore-plus/issues/63

Fix Aliased signals

---

.github/workflows/test_and_deploy.yml
pymmcore_plus/install.py

This is possible now with the new download URLs from https://github.com/micro-manager/download-mm/issues/2
Also update the github action caching to update monthly as new caches will not longer be triggered as often by updating the version and release strings in the install.py file. 
It is also now possible to manually specify both the version and the release. Also, previously the `--release` arg had no effect which should be fixed.

Download latest MM by default

---

pymmcore_plus/_tests/test_core.py
pymmcore_plus/core/_mmcore_plus.py

As for the `guessObjectiveDevices()` method, maybe it is good to have the `getOrGuessChannelGroup()` method returning a list of possible match instead of just the first one that is found (it is possible to have more than one channel group match using the regex `re.compile("(chan{1,2}(el)?|filt(er)?)s?", re.IGNORECASE)`)
The updated method can be like this:
```
chan_group = self.getChannelGroup()
if chan_group:
return [chan_group]
channel_guess = []
for group in self.getAvailableConfigGroups():
if self._channel_group_regex.match(group):
channel_guess.append(group)
return channel_guess
```

getOrGuessChannelGroup -> list

---

pymmcore_plus/client/callbacks/qcallback.py
pymmcore_plus/core/_mmcore_plus.py
pymmcore_plus/core/_signals.py

1. Add a `snap` method
This is a nice convenience that I've always wanted
2. Add an `imageSnapped` signal
This is will be nice for example when you have opened napari from ipython and are combining scripting and the GUI. e.g. I have some callback that modifies an overlay layer (i.e. cell detection) that I want to run whenever I snap an image either from the gui or from code.

Add a `snap` method and `signal`

---

pymmcore_plus/_tests/test_core.py

This test fails a lot because `ImageNumber` is sometimes 1... should have picked another item to test

Fix flaky metadata test

---

codecov.yml
examples/properties_and_state_events.py
pymmcore_plus/_tests/test_core.py
pymmcore_plus/core/_mmcore_plus.py

Akin to #38, when `core.setState()` is called it will _sometimes_ cause a `core.events.propertyChanged` event to be emitted, in a device-dependent manor.  (for example, in the demo config, it works for `Objective`, but not for `Dichroic`).  This pulls the logic from #38 into a more generally useful context manager and uses it for `setState` and `setStateLabel` as well

Ensure propertyChanged event occurs for setState and setStateLabel

---

pymmcore_plus/remote/client/callbacks/qcallback.py

in #98, I tried to reduce code duplication by subclassing QCoreSignaller in the remote module from the one in core.events.  I think this was _very_ rarely causing a change in event emission order in the tests. so I'm reverting that change until I learn more

undo subclass of QCoreSignaler in remote

---

pymmcore_plus/_tests/conftest.py
pymmcore_plus/_tests/test_core.py
pymmcore_plus/_tests/test_events.py
pymmcore_plus/core/_mmcore_plus.py

fixes #104
also creates and moves some tests.  The only new thing in the PR is the 6 lines in _mmcore_plus

Fix event emission when setting property on a state device

---

pymmcore_plus/_tests/test_events.py
pymmcore_plus/core/_mmcore_plus.py

uses pymmcore.g_keywords instead of strings for State and Label

use better globals for State and Label

---

README.md
docs/examples/mda.md
examples/qt_integration.py
examples/run_mda.py
pymmcore_plus/_tests/conftest.py
pymmcore_plus/_tests/test_core.py
pymmcore_plus/_util.py
pymmcore_plus/core/_mmcore_plus.py
pymmcore_plus/core/events/__init__.py
pymmcore_plus/core/events/_protocol.py
pymmcore_plus/core/events/_psygnal.py
pymmcore_plus/core/events/_qsignals.py
pymmcore_plus/mda/__init__.py
pymmcore_plus/mda/_engine.py
pymmcore_plus/mda/events/__init__.py
pymmcore_plus/mda/events/_protocol.py
pymmcore_plus/mda/events/_psygnal.py
pymmcore_plus/mda/events/_qsignals.py
pymmcore_plus/remote/_tests/test_client.py

As discussed in: https://github.com/tlambert03/pymmcore-plus/issues/101
Not polished yet - Opening for feedback from @tlambert03 
The big thing I struggled with was the relationship between core and the mda object should be. The mda engine needs to have access to core methods in order to function but then you can end up with this awful thing: `core._mda_engine._mmc._mda_engine._mmc.....`
If we decide to got this way then this should also get:
1. update the client to reflect the new structure.
2. Start of an `mda_tests` file
3. add an example showing how to define your own MDA engine.

Switch to user swappable mda-engines

---

.pre-commit-config.yaml
pymmcore_plus/_tests/test_events.py
pymmcore_plus/core/_mmcore_plus.py
pymmcore_plus/core/events/_protocol.py
pymmcore_plus/core/events/_psygnal.py
pymmcore_plus/core/events/_qsignals.py

This PR:
- adds a signal when the micromanager `autoshutter` state is changed
autoShutterSet = Signal(bool)
- add a signal when the selected shutter state is changed
shutterSet = Signal(shutter: str, bool)
used in https://github.com/tlambert03/napari-micromanager/pull/161

micromanager shutter and autoshutter signals

---

docs/examples/context-set.md
docs/index.md
pymmcore_plus/_tests/test_core.py
pymmcore_plus/core/_mmcore_plus.py

A reasonable extension to this (possibly to be included here) is to also allow setProperty to work. Currently it doesn't as this doesn't allow for multiple arguments.

add `setContext` method

---

pymmcore_plus/_tests/test_events.py
pymmcore_plus/core/_mmcore_plus.py
pymmcore_plus/core/events/_protocol.py
pymmcore_plus/core/events/_psygnal.py
pymmcore_plus/core/events/_qsignals.py

minor change in the `setShutterOpen()` method:
- fix annotations
- use `propertyChanged()` event  instead of `shutterSet` event. 
This is used in https://github.com/tlambert03/napari-micromanager/pull/161.

update setShutterOpen() method

---

pymmcore_plus/_tests/test_mda.py
pymmcore_plus/mda/_engine.py

previously the check wasn't working correctly if one of x or y was zero, then they would be incorrectly left in the current position.

fix: Make sure to set xy in mda even if they are 0

---

pymmcore_plus/_tests/test_core.py

not sure why it's failing on CI ... I can't reproduce on a windows computer locally

test: skip `test_lock_and_callbacks` on windows CI

---

pymmcore_plus/_logger.py
pymmcore_plus/_tests/conftest.py
pymmcore_plus/_util.py
pymmcore_plus/core/_mmcore_plus.py
pymmcore_plus/mda/_engine.py
pymmcore_plus/remote/client/_client.py
pymmcore_plus/remote/server/_pyrocore.py
pymmcore_plus/remote/server/_server.py

this PR uses a private loguru logger instead of the global one.  It's not a "endorsed" way to use loguru, but the standard method appears to leaves the logger open to the whims of any other library using loguru.  So, if they set the log level by using `logger.remove(); ...` then it can bonk whatever setup we've done.
so, after this, use `from pymmcore_plus._logger import logger`

feat: use private loguru logger

---

.github/workflows/test_and_deploy.yml
pymmcore_plus/core/events/_prop_event_mixin.py
pymmcore_plus/core/events/_qsignals.py

I had imported a type from a private psygnal module that is no longer exported in the recent psygnal version (naughty me).
This hides that import being TYPE_CHECKING
this also includes and closes #150

fix: fix missing typing import from psygnal

---

docs/conf.py

the move to `src` layout in #153 broke the api docs building

docs: fix api docs

---

.github/workflows/docs.yml
pyproject.toml

because of https://github.com/mkdocstrings/griffe/pull/115, I'm using a direct url for building docs, but twine didn't like that and rejected the last build.  So I'm only using it in the github build action here:

docs: remove direct griffe from extra

---

src/pymmcore_plus/_util.py
src/pymmcore_plus/core/_config.py
src/pymmcore_plus/core/_device.py
src/pymmcore_plus/core/_metadata.py
src/pymmcore_plus/core/events/__init__.py
src/pymmcore_plus/core/events/_norm_slot.py
src/pymmcore_plus/core/events/_prop_event_mixin.py
src/pymmcore_plus/core/events/_protocol.py

This vendors a private function from psygnal that we were using `_normalize_slot`.  (the purpose of the function is to retain the functionality of a callable without holding any strong references to a bound method)

fix: vendor private psygnal func

---

.pre-commit-config.yaml
docs/api/configuration.md
pyproject.toml
src/pymmcore_plus/__init__.py
src/pymmcore_plus/core/__init__.py
src/pymmcore_plus/core/_config.py
src/pymmcore_plus/core/_config_group.py
src/pymmcore_plus/core/_mmcore_plus.py
tests/test_config_group_class.py
tests/test_core.py

This adds a `ConfigGroup` object, akin to the `Device` and `Property` objects, that provide an object oriented API with a pythonic mutable mapping interface  (tests show how it works pretty well)

feat: add config group object

---

.github/workflows/test_and_deploy.yml
.pre-commit-config.yaml
README.md
docs/index.md
docs/install.md
pyproject.toml
src/pymmcore_plus/__init__.py
src/pymmcore_plus/_cli.py
src/pymmcore_plus/_util.py
src/pymmcore_plus/core/_mmcore_plus.py
src/pymmcore_plus/install.py
tests/conftest.py
tests/test_cli.py

replacement for `python -m pymmcore_plus.install` ... with the ability to extend lots of stuff
```zsh
╰─❯ mmcore --help
Usage: mmcore [OPTIONS] COMMAND [ARGS]...
mmcore: pymmcore-plus command line (v0.6.3.dev2+g37a0cf7).
For additional help on a specific command: type 'mmcore [command] --help'
╭─ Options ──────────────────────────────────────────────────────────────────────────────────╮
│ --version          Show version and exit.                                                  │
│ --help             Show this message and exit.                                             │
╰────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Commands ─────────────────────────────────────────────────────────────────────────────────╮
│ clean       Remove all …
```

feat: add `mmcore` command line program

---

src/pymmcore_plus/core/events/_prop_event_mixin.py

fixes a bug I'm seeing on napari-micromanager... must be due to duplicate cleanup races.

fix: fix _PropertySignal cleanup

---

src/pymmcore_plus/core/_mmcore_plus.py
tests/test_events.py

`pymmcore` `setChannelGroup` currently does not have/emit any signal when is called. 
This PR adds core `channelGroupChanged.emit()` to the `setChannelGroup` method.

feat: emit channelGroupChanged signal when calling setChannelGroup

---

src/pymmcore_plus/core/_mmcore_plus.py
tests/remote/test_client.py
tests/test_core.py

The `snap_with_shutter` function added in https://github.com/pymmcore-plus/pymmcore-widgets/pull/121/files (which made sure to emit shutter open signals before and after a snap event) should have been added to core instead of widgets.  This PR adds it, and adds a test

fix: fix snap emission events

---

docs/contributing.md
src/pymmcore_plus/_build.py
src/pymmcore_plus/_cli.py

with this PR, devs with apple silicon should be able to run
```
mmcore build-dev
```
to get working demo camera and utilties

feat: add build-dev command to build dev dependencies on apple silicon

---

pyproject.toml

Use `PyQt6` instead of `PyQt5` in `pyproject.toml` for testing so it works also on Apple Silicon.

test: use PyQt6 for testing

---

src/pymmcore_plus/_util.py
tests/test_misc.py

Since it's a common thing to retry stuff a couple times in MMCore, this adds a utility to help with it:
```python
from pymmcore_plus._util import retry
@retry(exceptions=RuntimeError, delay=0.5, logger=print)
def autofocus(core) -> float:
core.fullFocus()
core.waitForSystem()
return core.getZPosition()
```

feat: add general retry utility

---

src/pymmcore_plus/__init__.py
src/pymmcore_plus/core/_mmcore_plus.py
src/pymmcore_plus/mda/_runner.py
tests/test_mda.py

This changes the signature of MDARunner.run from 
```py
def run(self, sequence: MDASequence) -> None:
```
to 
```py
def run(self, events: Iterable[MDAEvent]) -> None:
```
as discussed elsewhere, this is the more powerful approach, and doesn't tie the engine to sequences of known length/shape, etc...  So, it could accept _any_ custom sequence/generator/iterable of `useq.MDAEvent` (which includes instances of `MDASequence`.)
The only tricky bit were the `setup_sequence` callback and `sequenceStarted` signal.  To avoid breaking uses like @ianhi 's [engine](https://github.com/ianhi/raman-mda-engine/blob/f7238bc286aa9642331eb5c6215c458e31327115/raman_mda_engine/_engine.py#L214) ... When a non `MDASequence` object is passed to `run()`, a mock `GeneratorMDASequence` is created and passed to …

refactor: relax signature of `MDARunner.run` to `Iterable[MDAEvent]`

---

src/pymmcore_plus/core/_device.py
src/pymmcore_plus/core/_mmcore_plus.py

The device object has nice logic to improve error messages in the case of failed device loading.  This moves that logic to the core class itself

refactor: move loadDevice logic from Device to MMCorePlus

---

src/pymmcore_plus/mda/_engine.py
tests/test_sequencing.py

This increases the duration of a sequence that can be run, by popping images off the circular buffer as it is running

perf: Pop images from circular buffer during sequence

---

.github/workflows/test_and_deploy.yml
src/pymmcore_plus/core/_sequencing.py
tests/test_sequencing.py

This fixes a bug in `canSequenceEvents` when one of the two events has an x,y, or z position of 0

fix: fix bug in sequencing

---

src/pymmcore_plus/mda/_engine.py
src/pymmcore_plus/mda/_runner.py

This makes sure that the `frameReady` signal emits (`np.ndarray`, `MDAEvent`) with the subevents inside of a sequenced event, (rather than the second item in the tuple always being   the combined `SequencedEvent`

fix: fix payload for sequenced objects

---

tests/test_mda.py

cc @fdrgsp, have a look at the diff here.
This is a tricky one.  I'm changing the test to only use public methods of external libraries (useq in this case).  Rather than asserting the private attribute of an external library `mda._fov_size`, I assert that the public method `mda.set_fov_size` has been called.  In other words, this treats useq schema as a complete black box with a set of public methods

test: don't test private attribute of useq

---

src/pymmcore_plus/mda/_runner.py
tests/conftest.py
tests/test_core.py

part of #229 ... but I'm going to leave that issue open, because I think the word "events" is still overloaded (we have both MDAEvents as well as Psygnal/QtEvents) ... I think we should probably rename `.events` to `.signals` everywhere, but that's a bigger change

refactor: rename _events to _signals in Runner

---

pyproject.toml
src/pymmcore_plus/_cli.py
src/pymmcore_plus/_logger.py
src/pymmcore_plus/_util.py
src/pymmcore_plus/core/_mmcore_plus.py
src/pymmcore_plus/mda/_engine.py
src/pymmcore_plus/mda/_runner.py
tests/conftest.py

closes #238 
we don't use many of the loguru features, and it brings on an unneeded extra dependency, and the possibility of conflict with stdlib logging

refactor: remove loguru

---

.github/workflows/test_and_deploy.yml
README.md
docs/index.md
docs/install.md
pyproject.toml
src/pymmcore_plus/_cli.py
src/pymmcore_plus/install.py
tests/test_cli.py

This follows on #239 to make Typer and rich (cli dependencies) only necessary when using the `mmcore` CLI.
now, use `pip install pymmcore-plus[cli]` to get that functionality
cc @wl-stepp

build: make cli dependencies (typer and rich) optional

---

README.md
docs/guides/migrating_pycro.md
docs/guides/pycromanager_migration.md
mkdocs.yml

This guide provides some API translation between pycromanager and pymmcore-plus
@hinderling, this was partially motivated by your comment at the end of the talk last week.  Hope this clarifies how some of the APIs of pycromanager and pymmcore-plus relate to each other!

docs: add migration info for pycro-manager users

---

src/pymmcore_plus/core/_mmcore_plus.py
tests/test_core.py

in #214 we  updated the original `pymmcore` `saveSystemConfiguration` method so that it also saves any pixel size configuration if are set. 
However it is not done properly, it assumes that the objective device e is called "Objective" and it does not take into account any other possible device-property that might be added to the pixel size configuration.
This PR fixes this issue and saves any `device-property-value` that are added to the pixel size `configuration.
---
For example, if we have a px config that is called `cfg1` and we call:
```py
getPixelSizeConfigData(cfg1).dict()
```
we might get something like this: 
``` py
{'Core': {'XYStage': 'XY'}, 'Objective': {'Label': 'Nikon 10X S Fluor'}}
```
Since in the px configuration we have two devices (`Core` and `Objective`), we need to …

fix: fix a bug in saveSystemConfiguration method

---

src/pymmcore_plus/core/_mmcore_plus.py
src/pymmcore_plus/mda/_engine.py
src/pymmcore_plus/mda/_protocol.py
src/pymmcore_plus/mda/_runner.py
src/pymmcore_plus/mda/events/_protocol.py
src/pymmcore_plus/mda/events/_psygnal.py
src/pymmcore_plus/mda/events/_qsignals.py

This emits a (currently-unstructured) metadata dict as the third value of frameReady.  This would be an important component for a proper writer spec (#29) 
It also adds `getTaggedImage` to mimic the Java API.
i should note that I don't really like the `getTaggedImage` API (the "tags" themselves are constructed in a way that makes them hard to disambiguate).  But for now, this uses it in case it helps with cross-compatibility
side-note: because both psygnal and qt let you connect a slot that accepts less values than the signal emits, we can always add positional arguments to signals without breaking any APIs.
closes #220

feat: add metadata to frameready signal, add getTaggedImage

---

src/pymmcore_plus/core/_mmcore_plus.py
src/pymmcore_plus/model/_device.py

fixes a bug @fdrgsp  found in the config wizard on a real device

fix: don't check is_busy when updating device in model

---

src/pymmcore_plus/_util.py
tests/test_misc.py

lets the user specify an emitter signal to any method on the listener

feat: add name_map to listeners_connect

---

src/pymmcore_plus/core/_mmcore_plus.py

closes #261 
```python
In [1]: core = CMMCorePlus()
In [2]: core is CMMCorePlus.instance()
Out[2]: True
```
doesn't seem to affect any tests

feat: make first instance of CMMCorePlus the global instance

---

src/pymmcore_plus/core/_mmcore_plus.py
src/pymmcore_plus/core/_state.py
tests/test_core.py

this is a better implementation of `CMMCorePlus.state`.  it could be used instead of `getTags` for metadata during acquisitions.  The output is typed by `TypedDicts` so it's easy to tell what keys are available in downstream usage, and the presence of each key is toggleable for performance reasons.
It adheres pretty tightly to the naming conventions in Core itself, and avoids coming up with new keys/conventions/capitalizations whenever possible
<details>
<summary>example output</summary>
```python
{
'Devices': {
'DHub': {},
'Camera': {
'AllowMultiROI': '0',
'AsyncPropertyDelayMS': '2000',
'AsyncPropertyFollower': '',
'AsyncPropertyLeader': '',
'Binning': '1',
'BitDepth': '16',
'CCDTemperature': '0.0000',
'CCDTemperature RO': '0.0000',
'CameraID': 'V1.0',
'CameraName': …
```

refactor: update state method on MMCorePlus

---

src/pymmcore_plus/_cli.py
src/pymmcore_plus/install.py
tests/test_cli.py

This PR makes all of the pretty rich stuff optional when calling `install.install()`.  The motivation is to make it easier to call `install.install()` from a GUI, without having to parse all the crazy rich output to give some basic feedback.

feat: make pretty output optional when using `mmcore install`

---

src/pymmcore_plus/mda/_engine.py
src/pymmcore_plus/mda/_protocol.py
tests/test_mda.py

This relaxes the engine `exec_event` protocol slightly to `(self, event: MDAEvent) -> Iterable[PImagePayload]:` (from `-> Sequence:`.  This allows frames to be yielded immediately as they are popped from the buffer
helps with #289

refactor: change exec_events to iterable

---

pyproject.toml
src/pymmcore_plus/seq_tester.py
tests/test_sequencing.py

This PR just adds some code to be able to decode SequenceTester images, similar to what @marktsuchida added in https://github.com/micro-manager/micro-manager/blob/main/systemtest/SequenceTests/test/org/micromanager/testing/TestImageDecoder.java

feat: Add basic msgpack decoding for images from SequenceTester 

---

src/pymmcore_plus/_util.py
src/pymmcore_plus/model/_device.py
tests/test_model.py

This is a partial fix to a bug in the pymmcore-widgets ConfigWizard that results in some hub devices (like SequenceTester) not showing any peripherals.
The problem is that some hub devices reveal their peripherals as top level library devices, while others may wait until after device initialization to reveal them.
What this PR does is to make sure that calling `Microscope.load_available_devices()` will not only check `getAvailableDevices` for all `getDeviceAdapterNames` ... but will *also* check `getInstalledDevices` for all `getLoadedDevicesOfType(DeviceType.Hub)`.  
it's not a complete for for widgets though, since the ConfigWizard will still need to call `model.load_available_devices()` after successfully initializing a hub device (which will happen over in that repo)

fix: fix available_peripherals for loaded hub devices

---

src/pymmcore_plus/model/_device.py
tests/test_model.py

fixes a silly bug in my code that fails to link available peripherals with their parent hub device when the library has multiple hubs.  Test will only work locally for now as it uses the Ti2 device adapter, but we can probably find another example of a multi-hub library that's easy to test.

fix: fix available peripherals for libraries with multiple hubs

---

.gitignore
src/pymmcore_plus/mda/handlers/_ome_zarr_writer.py

I had the problem that reading appending and re-writing the frame meta data become pretty slow for long acquisitions. First simple approach here to gather the metadata during the acqusition and write it on sequenceFinished.
Tests passing locally, not sure if frame metadata is tested though. Can have a look next week.

fix: fix excess reading of frame metadata in OMEZarrWriter

---

src/pymmcore_plus/mda/_engine.py

see conversation in #318 
This PR adds a `post_sequence_started` method to the `MDAEngine` that can be reimplemented by subclasses to perform custom behavior after `startSequencedAcquisition` is called by core.  the default implementation does nothing

feat: add post_sequence_started

---

src/pymmcore_plus/core/_mmcore_plus.py
src/pymmcore_plus/mda/_engine.py
tests/test_core.py

Metadata handling in the MDA engine is still a bit haphazard.  We largely copied the state of things in MM-studio, and discussions with multiple MM core devs has suggested that perhaps that isn't necessarily the best approach.  MM grabs a *lot* of metadata for every frame, much of which doesn't change over the course of the experiment, and it also will almost always match the metadata in the `MDAEvent` "command" that triggered that given frame.   Nico has suggested that this comes at a pretty big penalty, especially for very fast acquisition.
While this PR doesn't really formalize any approach just yet it does two things:
1) establishes two methods in the MDAEngine that are more easy for a subclass to override and customize:
- `get_summary_metadata()` - called once at the beginning
- …

refactor!: more minimal, and overrideable MDA metadata

---

src/pymmcore_plus/core/_mmcore_plus.py
src/pymmcore_plus/core/events/_protocol.py
src/pymmcore_plus/core/events/_psygnal.py
src/pymmcore_plus/core/events/_qsignals.py

this closes #144 by moving the `imageSnapped()` event from the `CMMCorePlus.snap()` method (which is new and unexpected for most people) to the `snapImage()` method (which is both more familiar and semantically correct).
This change is partially motivated by the confusion caused by this in https://github.com/pymmcore-plus/napari-micromanager/issues/305
Some considerations before merge:
1. since `snapImage()` no longer has access to the resulting image, it removes the numpy array as an argument to the callback, which is a breaking change.  Callbacks must now call `core.getImage()` themselves to retrieve the waiting image.  A [github code search](https://github.com/search?type=code&auto_enroll=true&q=imageSnapped.connect) result suggests we're the only ones using it, so not a big deal... …

refactor: move imageSnapped event

---

src/pymmcore_plus/mda/handlers/_ome_tiff_writer.py
tests/test_handlers/test_ome_tiff.py

this PR allows the `OMETiffWriter` to output a basic ImageJ hyperstack if the filename doesn't include `.ome.`.  The main difference is the requirement that the data be passed to tifffile must be in `tzcyxs` order

feat: support basic ImageJ hyperstack

---

src/pymmcore_plus/core/_mmcore_plus.py
src/pymmcore_plus/mda/_runner.py
tests/test_handlers/test_image_sequence_writer.py
tests/test_handlers/test_ome_zarr.py

This implements option number 1 and closes #311 
```python
core = CMMCorePlus()
core.mda.run(..., output='some/path.ome.zarr')  # pass a string
my_writer = CustomDataHandler()
core.mda.run(..., output= my_writer). # pass a data handler object 
```
The argument would be either:
- `str` - in which case a builtin Handler would be used based on extension.  Note that fsspec can be used to support remote filesystems.
- `ome.zarr` - > `OMEZarrWriter`
- `ome.tiff` -> `OMETiffWriter`
- `dir` -> no extension would use `ImageSequenceWriter`
- A Handler object, (anything implementing the data handler protocol, meaning it has at least a `frameReady` method that accepts 1-3 arguments).  This could be, for example, something that would deskew and rotate images prior to writing them.

feat: Add file saving `output` argument to MDARunner.run

---

src/pymmcore_plus/mda/handlers/_ome_zarr_writer.py

#265 accidentally added `import zarr` to the top level, meaning zarr was now required for running *any* mda.  this fixes that

fix: remove zarr dependency

---

src/pymmcore_plus/_cli.py
src/pymmcore_plus/_util.py
tests/test_cli.py

```shell
❯ mmcore info
python            : 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ]
platform          : macOS-14.2.1-arm64-arm-64bit
pymmcore-plus     : 0.8.8.dev2+gd6373b0
pymmcore          : 11.0.0.71.0
core-version-info : MMCore version 11.0.0
api-version-info  : Device API version 71, Module API version 10
mm_devices        : ~/Library/Application Support/pymmcore-plus/mm/Micro-Manager-258aa5ac8
useq-schema       : 0.4.7
tifffile          : 2023.9.26
zarr              : 2.16.1
```

feat: add `mmcore info` command

---

tests/conftest.py
tests/test_core.py
tests/test_events.py
tests/test_mda.py
tests/test_misc.py

we use Qt for testing, both to check our support for running within a Qt event loop, and also because the pytest-qt `qtbot` fixture is a convenient way to assert signals are emitted, *even with psygnal*.
It's long been [on my todo list](https://github.com/pyapp-kit/psygnal/issues/46) to bring something like `qtbot.waitSignals` to psygnal, but until I do that, we'll need to use pytest-qt. 
This PR makes it possible to test stuff without Qt, just skipping those tests for now.  which might be handy for #331

test: allow testing without Qt installed 

---

.github/workflows/test_and_deploy.yml
src/pymmcore_plus/_build.py
src/pymmcore_plus/_cli.py
tests/test_cli.py
tests/test_model.py
tests/test_sequencing.py

related to #87
while `mmcore install` won't work for linux, `mmcore build-dev` will.  But, it's not the "full package" with all the device adapters, so I'm not marking it as solved yet
closes #310  because it also allows the device list to be specified at build time
**update**:
while the original intent of this PR was just to get device adapters building on linux, it has expanded into a PR that makes a lot of general improvements to `mmcore build-dev`
- works for mac and linux now
- accepts any list of device adapters: `mmcore build-dev DemoCamera SequenceTester ...`
- will validate those device adapter names early in the process
- better fetching of git sha for early detection of existing destination directory
- better modification of the configure.ac and makefile.am files (no more local …

feat: support linux on `mmcore build-dev`, test on linux, make device list editable

---

.github/workflows/test_and_deploy.yml

should speed up tests
to invalidate the cache, either add an additional (arbitrary) string to cache key, or to the the `_build.py` file

ci: cache built drivers for all platforms

---

pyproject.toml
src/pymmcore_plus/mda/_engine.py
src/pymmcore_plus/mda/handlers/_5d_writer_base.py
src/pymmcore_plus/mda/handlers/_ome_tiff_writer.py
src/pymmcore_plus/mda/handlers/_ome_zarr_writer.py
tests/io/test_ome_zarr.py

some quality of life updates for the 5D writer base and OmeZarrWriter that should help when using as a datastore for display.  This PR mostly adds:
```python
writer = OMEZarrWriter()
writer.as_xarray()
writer.isel(t=0, c=1, x=slice(100,200))
```

feat: update 5d writer with isel method, make zarr output nicer to xarray, add a bit more metadata

---

examples/tensorstore_mda.py
pyproject.toml
src/pymmcore_plus/mda/handlers/__init__.py
src/pymmcore_plus/mda/handlers/_tensorstore_handler.py
src/pymmcore_plus/mda/handlers/_tensorstore_writer.py
tests/io/test_zarr_writers.py

This writer/handler is similar to (and I suspect will eventually replace) the `OMEZarrWriter`.  It uses tensorstore to write to disk, which in my quick-and-dirty benchmarks seems to be writing about 3x faster than python-zarr (note, i haven't tried to tune the python-zarr much to make it faster, but tensorstore is written in C++ and is explicitly designed to take care of multi-threading, and just generally be performant).  
Tensorstore supports a number of formats, though zarr is what we'll likely use the most. I'm not currently worrying about writing out to the ngff spec, as this writer is designed to handle more than 5 dimensions easily (since tensorstore also supports that nicely) and I don't want to artificially restrict it yet... we can add an ome-zarr variant in the future.
This …

feat: add tensorstore writer

---

src/pymmcore_plus/mda/_engine.py
src/pymmcore_plus/mda/_runner.py

(hopefully) fixes #352 
@linshaova i've made a couple additional changes here that (technically) undo some of changes I made in #307, but I think it's a better overall fix.  basically, I've moved all of the `core.stop<Thing>Sequence` calls into the `teardown_event` event method of the engine (which always gets called at the end of an event) and removed the "safety" calls to `stop<Thing>Sequence` from the setup_event method.  I've also added a couple more `stop<Thing>Sequence` calls for XYStageDevice and ExposureSequence.
If you have a moment, it would be great if you confirm whether this branch fixes your issues

fix: add stopPropertySequence before loadPropertySequence in setup_sequenced_event

---

tests/test_bench.py

adds benchmarks for summary and frame metadata during an MDA

perf: benchmark metadata

---

tests/test_cli.py

in preparation for the next useq-schema release, this uses only pydantic v2 syntax

refactor: use only pydantic2 syntax

---

docs/api/utils.md
docs/install.md
src/pymmcore_plus/__init__.py
src/pymmcore_plus/_cli.py
src/pymmcore_plus/_util.py
tests/test_cli.py

this adds an `mmcore use` command line, along with an `pymmcore_plus.use_micromanager()` function to set the activate micromanager directory if you have multiple installed:
```sh
$ mmcore list
📁 /Users/talley/Library/Application Support/pymmcore-plus/mm
* Micro-Manager-80d5ac1 (active)
• Micro-Manager-2.0.3-20240217
$ mmcore use 20240217
using /Users/talley/Library/Application Support/pymmcore-plus/mm/Micro-Manager-2.0.3-20240217
$ mmcore list
📁 /Users/talley/Library/Application Support/pymmcore-plus/mm
* Micro-Manager-2.0.3-20240217 (active)
• Micro-Manager-80d5ac1
```

feat: add `mmcore use` to set the active micro-manager installation

---

docs/guides/mda_engine.md
pyproject.toml
src/pymmcore_plus/mda/_engine.py
tests/conftest.py

we've had a couple cases where people got unexpectedly slow performance, and enabling hardware sequencing was the solution.  I think it's stable enough to make it True by default, but tests still need to enable it explicitly.
cc @simonecoppola

feat: enable hardware sequencing by default

---

.github/workflows/ci.yml
.pre-commit-config.yaml
pyproject.toml
src/pymmcore_plus/mda/_runner.py
src/pymmcore_plus/mda/handlers/_tensorstore_handler.py
src/pymmcore_plus/mda/handlers/_util.py
tests/test_mda.py

closes #380 by supporting the new reset_event_timer attribute in useq schema
pre-commit will fail until useq 0.5.1 (releasing now)

feat: add support for reset_event_timer

---

src/pymmcore_plus/core/events/_device_signal_view.py
src/pymmcore_plus/core/events/_prop_event_mixin.py
src/pymmcore_plus/core/events/_protocol.py

This pull request includes changes to improve the flexibility of the `disconnect` method across multiple files by allowing it to accept `None` as an argument, which disconnects all slots if provided.

fix: fix typing on Signal.disconnect protocol

---

src/pymmcore_plus/install.py

When `mmcore build` fails due to unsupported platform (e.g. Linux), give a hint that the `mmcore build-dev` command also exists to build Micro-Manager from source.

Add a hint about the mmcore build-dev command

---

.github/workflows/ci.yml
pyproject.toml
src/pymmcore_plus/mda/handlers/_tensorstore_handler.py
src/pymmcore_plus/metadata/functions.py

It looks like something about Qt6.8 has broken the MDARelayThread pattern in the context of Qt signals.  Specifically, this connection here never gets triggered when the Sequence starts:
https://github.com/pymmcore-plus/pymmcore-plus/blob/8ebd4743b5ca10f4ccf055cafe11a0270600f4d9/src/pymmcore_plus/mda/_thread_relay.py#L86
not sure what changed in 6.8, but for now this just pins the version of pyside6 in testing by adding an extra

test: fix tests by pinning pyside<6.8

---

src/pymmcore_plus/_logger.py

This PR checks if rich is installed (and it will be if the cli is also installed) and uses it to make much nicer colored logs.  Its a nicer/lighter solution than the original loguru thing that was removed in #239
without rich:
with rich:

feat: use rich for logging if available

---

.github/workflows/ci.yml
pyproject.toml
tests/io/test_zarr_writers.py

will fail until wheels pymmcore wheels are released to pypi.  See https://github.com/micro-manager/pymmcore/pull/122

ci: support python 3.13

---

src/pymmcore_plus/mda/_engine.py
src/pymmcore_plus/metadata/functions.py
src/pymmcore_plus/metadata/schema.py
tests/test_sequencing.py

This PR makes it so that the MDAEngine doesn't query stage positions during sequenced/triggered acquisitions by default.  This can be a rather slow call, depending on the stage, and ultimately was at the heart of @simonecoppola's performance issues seen in https://github.com/pymmcore-plus/pymmcore-plus/issues/379 (thank you **SO** much Simone for debugging that).
this PR adds:
```python
MDAEngine:
include_frame_position_metadata: Literal[True, False, "unsequenced-only"] = "unsequenced-only"
```
which gate whether or not we ask for position.  This is not a "generalizable" solution, as was discussed at the end of #358 (in that it doesn't add a more generic pattern for pruning metadata as desired), but it gets something down for now.
note that `FrameMetaV1.position` now becomes an …

perf: don't query position on triggered acquisition frames by default, add `include_frame_position_metadata` flag

---

.gitignore
pyproject.toml
src/pymmcore_plus/core/_mmcore_plus.py
tests/conftest.py
tests/io/test_zarr_writers.py
tests/test_cli.py
tests/test_core.py
tests/test_mda.py
tests/test_sequencing.py

this test fixes an annoying issue i've been having (only in local tests, not on CI) where i can end up with `OSError: [Errno 24] Too many open files:` by the end of the tests.  Turns out this was caused by configuring logging to files in the `test_cli_logs` test, as well as the core singleton persisting after tests.  This partially neuters the `test_cli_logs` test, but makes the tests overall cleaner

test: fix file descriptor leaks, and other misc things

---

pyproject.toml
src/pymmcore_plus/core/_mmcore_plus.py
tests/test_core.py

this PR removes the few methods in `CMMCorePlus` that had been decorated with wrapt `@synchronized`.  I'm not convinced they were necessary (there's plenty of thread safety already implemented on the C++ side), and it's definitely possible that they were adding to overhead, particularly on commonly called functions like `snapImage`.

refactor: remove wrapt synchronized

---

src/pymmcore_plus/_util.py
src/pymmcore_plus/core/_mmcore_plus.py
tests/test_core.py

Extends the `describe()` method to show more stuff
```python
core.describe(show_config_groups=True)
```
```python
core.describe( show_available=True)
```

feat: enhance describe method to include configuration groups and available devices

---

src/pymmcore_plus/_benchmark.py
src/pymmcore_plus/_cli.py
tests/test_cli.py

this adds a simple Device benchmarking cli tool `mmcore bench` that lets you check various method calls to different devices, which may help to determine slow calls for various devices:
here is an example output (it adds rows as they appear in realtime):
```sh
$ mmcore bench --config .\tests\cbmf-hardware.cfg
```

feat: Add `mmcore bench` to CLI

---

src/pymmcore_plus/mda/_runner.py
tests/test_mda.py

This fixes #418  (and is pulled out of #400).
When the user is directly passing an iterator object, such as `iter(queue.get, None)` to `MDARunner.run`, we don't want the MDAEngine to do complicated things like try to setup hardware triggering.  This PR essentially implies that using queues and passing iterables is an advanced use case, and we don't want to inject additional "magic".  This *does* mean that queue users won't be able to use hardware triggering (for now) but that will be solved by asking them to explicitly opt in to hardware triggering by passing in a special SequencedEvent subclass of `MDAEvent` ... more on that in #400

fix: Don't use `Engine.event_iterator` when an Iterable is directly passed to `MDARunner.run`

---

src/pymmcore_plus/mda/_engine.py
tests/test_mda.py

This commit resolves a bug where the properties of the MDAEvent (as per the useq-schema specification) are not being set when only one event is sent to the MDA engine or when an event-driven acquisition engine is used.
The fix explicitly sets the properties using mmc.setProperty within the setup_single_event method of the MDAEngine. 
- Tests were conducted using TestProperty1 and TestProperty2 on a simulated camera device.
- The fix also works on a real attached device.
Apologies if this commit doesn't fully align with the contributing guidelines. I encountered difficulties setting up the environment, particularly with pymmcore failing to build on Windows. Below is the error I received:
```
Microsoft (R) Library Manager Version 14.42.34436.0
Copyright (C) Microsoft Corporation.  All …
```

Fix Issue with useq MDA Event Properties Not Being Set in MDAEngine

---

src/pymmcore_plus/mda/__init__.py
src/pymmcore_plus/mda/_runner.py
src/pymmcore_plus/mda/handlers/__init__.py
src/pymmcore_plus/mda/handlers/_img_sequence_writer.py
src/pymmcore_plus/mda/handlers/_tensorstore_handler.py
tests/test_mda.py

this PR adds `MDARunner.get_output_handlers`.  It solves an issue that @fdrgsp and I came across while trying to display data using ndv during the course of an MDA.  Namely: it's not easy to get a pointer to where the data is being stored/ written from the `core.mda` object unless you yourself created them and passed them in.  So this solves two use cases:
someone starts an mda with either:
```python
core.mda.run(..., output='some_path.zarr')
handler = TensorStoreHandler()
core.mda.run(..., output=handler)
```
Here, the runner will maintain a weak reference to either the explicitly passed `handler`, or the handler that was implicitly created to deal with the provided path.  These can be retrieved all the way from `sequenceStarted` to `sequenceFinished` using the new …

feat: add `get_output_handlers` method to `MDARunner`

---

src/pymmcore_plus/core/_constants.py
src/pymmcore_plus/model/_config_file.py
tests/test_model.py

When loading a config file, this PR makes an error on all commands except load device set property be warnings instead of exceptions

fix: turn most exceptions to warnings when loading config file into a model

---

src/pymmcore_plus/core/_mmcore_plus.py
src/pymmcore_plus/core/events/_protocol.py
src/pymmcore_plus/core/events/_psygnal.py
src/pymmcore_plus/core/events/_qsignals.py
tests/test_events.py

closes #429 by emitting signals *before* calling `core.startContinuousSequenceAcquisition` and `core.startSequenceAcquisition`.  So that users can take action before the call is passed to the devices, for example, to begin a sequence on another non-MM-controlled device.
cc @dpshepherd

feat: add continuousSequenceAcquisitionStarting and sequenceAcquisitionStarting signals

---

pyproject.toml
src/pymmcore_plus/mda/_engine.py
tests/test_mda.py

This will be necessary for anyone who uses CustomAction added in useq-schema v0.7.0: https://github.com/pymmcore-plus/useq-schema/pull/214
That's a generic escape hatch for anyone who wants to have an MDAEvent that does something other than acquire an image... We don't want MDAEngine to do anything with it (users will need to subclass and handle it themselves in the `exec_event` method of their custom engine)
cc @dpshepherd

chore: support useq 0.7, don't try to exec anything but AcquireImage

---

src/pymmcore_plus/_pymmcore.py
src/pymmcore_plus/core/_metadata.py
src/pymmcore_plus/core/_mmcore_plus.py
tests/test_core.py

fixes #435
This also fixes what should have been a fine call to `md = Metadata(md)` by making `pymmcore_plus.Metadata` behave *both* as a subclass of `pymmcore.Metadata`, and also a (virtual) subclass of `abc.collections.Mapping`

fix: Fix missing metadata in popNextImageAndMD

---

src/pymmcore_plus/core/_mmcore_plus.py
src/pymmcore_plus/mda/_engine.py
tests/test_sequencing.py

This might speed up https://github.com/pymmcore-plus/pymmcore-plus/issues/445 ... @zbaker11, @ssalteko if you have time and are able/willing to install this branch, it would be good to know if this speeds up your use case.  Note: you would only notice a difference here for the single-channel case (i.e. where no actual config change is needed).
cc @fdrgsp

refactor: set config only when different

---

.github/workflows/ci.yml
src/pymmcore_plus/_pymmcore.py
src/pymmcore_plus/core/_constants.py
src/pymmcore_plus/core/_mmcore_plus.py
src/pymmcore_plus/metadata/functions.py
src/pymmcore_plus/metadata/schema.py
src/pymmcore_plus/model/_config_file.py
src/pymmcore_plus/model/_pixel_size_config.py
tests/test_model.py
tests/unicore/test_unicore.py
tests/unicore/test_xy_stage.py

the new version of pymmcore changes a  few things that break tests.  This fixes it.  see also https://github.com/micro-manager/pymmcore/pull/131

test: fixes for pymmcore v11.5

---

.github/workflows/ci.yml
pyproject.toml
src/pymmcore_plus/_util.py

this supports device adapters installed with `pip install mm-device-adapters` (https://github.com/pymmcore-plus/mm-device-adapters).  which makes it possible to get a fully working system just with `pip install pymmcore-plus mm-device-adapters`

feat: Support mm-device-adapters

---

.github/workflows/ci.yml
pyproject.toml
src/pymmcore_plus/_util.py

reverts the addition of mm-device-adapters to the testing suite from #455 
this also fixes a bug seen by @fdrgsp where, on windows, no micromanager is found (for python 3.11 and below) due to an error in check_device_interface... due to `ctypes.winDLL()` not accepting Path objects

chore: revert mm-device-adapters usage in tests

---

.github/workflows/ci.yml
.github/workflows/docs.yml
CHANGELOG.md
docs/contributing.md
pyproject.toml
uv.lock

This PR revamps  `pyproject.toml` to use dependency-groups, and updates all of the CI to use uv.
It checks in the uv lockfile (just for ease in development and testing... it doesn't actually lock any of the library dependencies).
it also test minimum stated dependencies during tests
note, for pip users, you should now use `pip install -e . --group dev` instead of `pip install -e .[dev]`

test: add uv lockfile and test with uv (including minimum deps)

---

.pre-commit-config.yaml
src/pymmcore_plus/core/__init__.py
src/pymmcore_plus/core/_device.py
src/pymmcore_plus/core/_mmcore_plus.py
tests/test_device_class.py

this adds `pymmcore_plus.core.Device` subclasses for each `DeviceType`, with device-type specific methods:
for example:
```python
In [1]: core = CMMCorePlus()
In [2]: core.loadSystemConfiguration()
In [4]: xy = core.getDeviceObject('XY')
In [5]: xy.position
Out[5]: (-0.0, -0.0)
In [6]: xy.position = (10, 20)
In [7]: xy.position
Out[7]: (10.004999999999999, 19.995)
In [10]: xy.getXYPosition()  # standard API alias
Out[10]: [10.004999999999999, 19.995]
In [12]: xy.isSequenceable()
Out[12]: False
```
cc @marktsuchida 
`core.getDeviceObject` also becomes type-safe.  If you know the type of the device for the label you're passing, you can pass either the `pymmcore_plus.core.Device` subclass, or the `DeviceType` enum and your IDE will know what subtype you're getting (and an exception will be …

feat: extend object-oriented device API

---

.github/workflows/ci.yml
pyproject.toml
src/pymmcore_plus/core/_mmcore_plus.py
tests/conftest.py
tests/test_cli.py
uv.lock

This fixes a latent bug that was exposed in pymmcore `11.5.1.73.0`:
If a `pymmcore.MMEventCallback` is registered with the core, and a pointer is not retained, then a segfault can occur when the c++ core destructor is called:
```python
core = pymmcore.CMMCore()
core.registerCallback(pymmcore.MMEventCallback())
del core  # <- boom
```
This PR:
1. makes sure to call `super().registerCallback(None)` in the `__del__` method, before calling `core.reset()`
2. makes it an error to call `registerCallback` at all... since it would break everything.  Users are instructed to connect to `core.events` instead 
also uses and closes #466

fix: dangling callback during core deletion, and disallow `registerCallback`

---

examples/unicore_camera.py
examples/unicore_hamamatsu.py
src/pymmcore_plus/experimental/unicore/__init__.py
src/pymmcore_plus/experimental/unicore/core/_unicore.py
src/pymmcore_plus/experimental/unicore/devices/_camera.py
tests/test_bench.py
tests/unicore/test_camera.py

CC @hinderling, if you had happened to start using this yet, I meant to call this class CameraDevice and not just Camera.  Will be releasing this shortly and will break your code if you already used the name Camera

refactor: rename Camera to CameraDevice

---

.github/workflows/ci.yml
src/pymmcore_plus/core/_mmcore_plus.py

related to https://github.com/pymmcore-plus/pymmcore-widgets/issues/454
https://github.com/micro-manager/mmCoreAndDevices/pull/659/files ... and pymmcore 11.9.0.73.0 have created problems for signal relaying specifically with pyside6.
This PR would simply ignore the new signals for now (since they all had direct pymmcore-plus emission anyway).
also adds tests for widgets and gui on pyside6

fix: fallback to old signal behavior for new image/sequence events

---

src/pymmcore_plus/core/_mmcore_plus.py

In snapImage().
We found a case where a widget (preset table) was assuming the device label to be valid (non-mepty) and failing. I think it's reasonable to suppress the signal entirely when there is no current shutter.

fix: Don't emit propertyChanged for empty shutter
